- name: Fetch Elasticsearch .deb
  command: wget {{ elurl }}-{{ ver }}.deb -O /tmp/elasticsearch-{{ ver }}.deb creates=/tmp/elasticsearch-{{ ver }}.noarch.rpm

- name: Install Elasticsearch from .deb
  command: dpkg -i --skip-same-version /tmp/elasticsearch-{{ ver }}.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')" # see http://stackoverflow.com/questions/19127493
