- name: Fetch Elasticsearch .deb
  command: wget {{ elurl }}-{{ ver }}.deb -O /tmp/elasticsearch-{{ ver }}.deb

- name: Install Elasticsearch from .deb
  command: dpkg -i --skip-same-version /tmp/elasticsearch-{{ ver }}.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')" # see http://stackoverflow.com/questions/19127493

- name: Create templates directory
  file: path=/usr/share/elasticsearch/config/templates owner=root group=root mode=0755 state=directory

# See http://www.elasticsearch.org/blog/new-in-logstash-1-3-elasticsearch-index-template-management/
# Due to a bug in Logstash 1.3.1 mapping this template stay temporary disabled.
#- name: Create Logstash mapping
#  template: src=elasticsearch-template.json dest=/usr/share/elasticsearch/config/templates/elasticsearch-template.json owner=root group=root mode=0644
#  notify:
#   - restart elasticsearch
